# Generated by Django 4.2.1 on 2023-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('CYBER AND TECHNICAL DEPARTMENT', 'CTD'), ('HEADQUARTERS', 'HQ'), ('EVALUATION ANALYSIS AND PRODUCTION', 'EAP'), ('COUNTER TERRORISM', 'CT')], max_length=255),
        ),
    ]
