# Generated by Django 4.2.1 on 2023-08-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevents',
            name='reportdepartment',
            field=models.CharField(blank=True, choices=[('CYBER AND TECHNICAL DEPARTMENT', 'CTD'), ('HEADQUARTERS', 'HQ'), ('EVALUATION ANALYSIS AND PRODUCTION', 'EAP'), ('COUNTER TERRORISM', 'CT'), ('Global Politics', 'Global Politics'), ('CRIME', 'Crime'), ('FIRE', 'Fire'), ('INCIDENT', 'Incident'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
    ]
