# Generated by Django 4.2.1 on 2023-08-05 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0004_alter_timelineevents_reportdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevents',
            name='createdby',
            field=models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
