# Generated by Django 4.2.1 on 2023-08-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_alter_timelineevents_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevents',
            name='eventtype',
            field=models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event'), ('INFORMATION', 'Information'), ('REPORT', 'Report'), ('PERSON', 'Person'), ('VEHICLE', 'Vehicle'), ('ORGANIZATION/BUSINESS', 'Organization/Business'), ('POLITICAL PARTY', 'Political Party')], default='INFORMATION', max_length=255),
        ),
        migrations.AlterField(
            model_name='timelineevents',
            name='newslink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
