# Generated by Django 4.2.1 on 2023-08-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_alter_timelineevents_eventtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevents',
            name='showinmap',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
