# Generated by Django 4.2.1 on 2023-08-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_alter_timelineevents_showinmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevents',
            name='eventtype',
            field=models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event'), ('INFORMATION', 'Information'), ('REPORT', 'Report'), ('PERSON', 'Person'), ('VEHICLE', 'Vehicle'), ('ORGANIZATION/BUSINESS', 'Organization/Business'), ('POLITICAL PARTY', 'Political Party')], default='', max_length=255),
        ),
    ]
